$(document).ready(function(){
    $(".design").click(function(){
      $("#design-image").toggle();
      $("#design").toggle();
    });
});
$(document).ready(function(){
    $(".dev").click(function(){
      $("#dev-image").toggle();
      $("#development").toggle();
    });
});
$(document).ready(function(){
    $(".product").click(function(){
      $("#product-image").toggle();
      $("#product").toggle();
    });
});

$(document).ready(function(){
    $("#work1").mouseenter(function(){
        $("#picture1").show();
      })
      .mouseleave(function(){
        $("#picture1").hide();
      });
    });
