$(document).ready(function(){
    $(".design").click(function(){
      $("#design-image").toggle();
      $("#design").toggle();
    });
});
$(document).ready(function(){
    $(".dev").click(function(){
      $("#dev-image").toggle();
      $("#development").toggle();
    });
});